### ISSUE TITLE
Remote I/O error

### ISSUE THREAD

**Issue by cschwarz007** [pimoroni/msa301-python#2]
Hi pimoroni Team,

I am using the MSA301 with a RPi3. In general, things work fine. BUt I do get a Remote I/O error once in a while, w. g. like this:

>Traceback (most recent call last):
  File "./detect-axis-move.py", line 27, in \<module\>
    'active_interrupt')))
  File "/usr/local/lib/python2.7/dist-packages/msa301/__init__.py", line 383, in wait_for_interrupt
    triggered_interrupt = self._msa301.MOTION_INTERRUPT.get_interrupts()
  File "/usr/local/lib/python2.7/dist-packages/i2cdevice/__init__.py", line 89, in \<lambda\>
    return lambda: self.device.get_field(self.register.name, name)
  File "/usr/local/lib/python2.7/dist-packages/i2cdevice/__init__.py", line 202, in get_field
    self.read_register(register.name)
  File "/usr/local/lib/python2.7/dist-packages/i2cdevice/__init__.py", line 174, in read_register
    self.values[register.name] = self._i2c_read(register.address, register.bit_width)
  File "/usr/local/lib/python2.7/dist-packages/i2cdevice/__init__.py", line 246, in _i2c_read
    for x in self._i2c.read_i2c_block_data(self._i2c_address, register, bit_width // self._bit_width):
IOError: [Errno 121] Remote I/O error

What am I doing wrong?

Many thanks for your support!
Christian

**Comment by Gadgetoid** [comment]
Sorry for the delay responding- I'm trying some new filters to cut through the noise in my GitHub issues backlog and it's turning up a few things that I've missed.

Are you still having this issue? It could be anything from an intermittent wiring error, to power instability to collissions with another i2c device on the same bus.

(or could just as equally be a flaw in my code!)
